// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/PluginRC/PluginRC.proto)


#if not defined(AEROX_IS_WINDOWS)

#include <iomanip>

#include <plugins/rc_passthrough/PluginRC.h>
#include <plugins/rc_passthrough/PluginRC_impl.h>

namespace mavsdk {

using RcChannels = PluginRC::RcChannels;

PluginRC::PluginRC(System& _system) : PluginBase(), impl_{std::make_unique<PluginRCImpl>(_system)}
{}

PluginRC::PluginRC(std::shared_ptr<System> _system) :
    PluginBase(),
    impl_{std::make_unique<PluginRCImpl>(_system)}
{}

PluginRC::~PluginRC() {}

void PluginRC::subscribe_rc_channels(RcChannelsCallback _callback)
{
    impl_->subscribe_rc_channels(_callback);
}

PluginRC::RcChannels PluginRC::rc_channels() const
{
    return impl_->rc_channels();
}

std::ostream& operator<<(std::ostream& str, PluginRC::RcChannels const& rc_channels)
{
    str << std::setprecision(15);
    str << "rc_channels:" << '\n';
    for(auto channel : rc_channels.channels)
        str << channel << '\t';
    str << '\n';
    str << "status: " << rc_channels.status ? "ok" : "ko";
    str << '\n';
    return str;
}

std::ostream& operator<<(std::ostream& str, PluginRC::Result const& result)
{
    switch (result) {
        case PluginRC::Result::Unknown:
            return str << "Unknown";
        case PluginRC::Result::Success:
            return str << "Success";
        case PluginRC::Result::NoSystem:
            return str << "No System";
        case PluginRC::Result::ConnectionError:
            return str << "Connection Error";
        case PluginRC::Result::Busy:
            return str << "Busy";
        case PluginRC::Result::CommandDenied:
            return str << "Command Denied";
        case PluginRC::Result::Timeout:
            return str << "Timeout";
        case PluginRC::Result::Unsupported:
            return str << "Unsupported";
        default:
            return str << "Unknown";
    }
}

} // namespace mavsdk

#endif
